# Generated by Django 4.0.6 on 2022-09-17 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnswerContent', models.TextField(verbose_name='Текст ответа')),
                ('DateCreation', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255, verbose_name='Имя')),
                ('SecondName', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('ThirdName', models.CharField(max_length=255, verbose_name='Отчество')),
                ('SocialStatus', models.CharField(max_length=255, verbose_name='Социальный статус')),
                ('PhoneNumber', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('EmailAddress', models.EmailField(max_length=255, verbose_name='Email')),
                ('PhysicalAddress', models.CharField(max_length=255, verbose_name='Адрес')),
                ('AppealContent', models.TextField(verbose_name='Текст обращения')),
                ('DateApplication', models.DateField(auto_now_add=True, verbose_name='Дата отправки')),
                ('DateRegistration', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryValue', models.CharField(max_length=255, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReportContent', models.TextField(verbose_name='Содержание отчёта')),
                ('DateCreation', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusValue', models.CharField(max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskContent', models.TextField(verbose_name='Содержание')),
                ('DateTasking', models.DateField(auto_now_add=True, verbose_name='Дата постановки')),
                ('CurrentAppeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appeal.appeal', verbose_name='Текущее обращение')),
                ('TaskStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appeal.status', verbose_name='Статус обращения')),
            ],
        ),
    ]
