# Generated by Django 4.0.6 on 2022-09-17 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='AppealStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appeal.status', verbose_name='Статус обращения'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='CategoryValue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appeal.category', verbose_name='Категория обращения'),
        ),
    ]
